### ISSUE TITLE
course card in the landing page is not well managed 

### ISSUE THREAD

**Issue by Atishdhungana** [SaumyaBhandari/contentManagementSystem#13]
![course card](https://user-images.githubusercontent.com/81402731/118349416-409e1a80-b570-11eb-8bea-ecb72ea8cbb7.png)
whenever, I add the course it shows like that as the picture is mentioned above. the card of the course is not so attractive and also the position is not maintained.

**Comment by Sabina9865** [comment]
Issue Solved
![Screenshot (563)](https://user-images.githubusercontent.com/81402847/118358626-78708680-b59f-11eb-92cd-042995d19a0f.png)
