### ISSUE TITLE
styling of course cards in landing page is not so attractive.

### ISSUE THREAD

**Issue by Atishdhungana** [SaumyaBhandari/contentManagementSystem#8]
the looks of card design is very outdated and unattractive.

**Comment by Sabina9865** [comment]
Issue solved

**Comment by Sabina9865** [comment]
Issue solved
![Screenshot (578)](https://user-images.githubusercontent.com/81402847/118360139-10716e80-b5a6-11eb-8d52-34f77230ea27.png)
